### ISSUE TITLE
Clearwater-monit  -- There is no service by that name

### ISSUE THREAD

**Issue by thomnico** [Metaswitch/clearwater-juju#21] opened 2015-06-09 09:27 UTC
Hello,

looks like an old issue resurecting.

For ALL the services test on fresh AWS install I got start failing due to this:

unit-clearwater-homestead-0[5169]: 2015-06-09 08:45:31 INFO unit.clearwater-homestead/0.start logger.go:40 clearwater-monit start/running, process 20549
unit-clearwater-homestead-0[5169]: 2015-06-09 08:45:32 INFO unit.clearwater-homestead/0.start logger.go:40 Action failed -- There is no service by that name

**Comment by rkd-msw** [comment] 2015-06-09 10:23
Hi Nicolas,

I've just created an OpenStack deployment and confirmed that the charms work for me, so I'm wondering if there's some difference in your environment. Can you confirm that you're using the dnsaas branch of clearwater-juju (commit e32ecb5b6a2538b51c41c9adcf36c391684f75b7)?

In terms of stability, the dnsaas branch hasn't changed since May 21st, and the Clearwater packages it uses have been stable since April 16th, so hopefully this will be a configuration/environment issue we can address quickly.

**Comment by thomnico** [comment] 2015-06-09 10:45
I do confirm

in Homestead  for example changing :
monit monitor homestead
in :
monit monitor homestead_process

Works !

Same for others looks like the monit naming has been changed but not tested.

Working on a pull request right away.



On Tue, Jun 9, 2015 at 12:23 PM, Rob Day <notifications@github.com> wrote:

> Hi Nicolas,
>
> I've just created an OpenStack deployment and confirmed that the charms
> work for me, so I'm wondering if there's some difference in your
> environment. Can you confirm that you're using the dnsaas branch of
> clearwater-juju (commit e32ecb5
> <https://github.com/Metaswitch/clearwater-juju/commit/e32ecb5b6a2538b51c41c9adcf36c391684f75b7>
> )?
>
> In terms of stability, the dnsaas branch hasn't changed since May 21st,
> and the Clearwater packages it uses have been stable since April 16th, so
> hopefully this will be a configuration/environment issue we can address
> quickly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Metaswitch/clearwater-juju/issues/21#issuecomment-110306407>
> .
>



-- 
Best Regards,
       Nicolas Thomas
http://insights.ubuntu.com/?p=889
EMEA Solution Architect              Canonical
GPG FPR: D592 4185 F099 9031 6590 6292 492F C740 F03A 7EB9

**Comment by rkd-msw** [comment] 2015-06-09 10:51
The change in Monit naming (homestead -> homestead_process) shouldn't affect the charms - the charms should be using the stable repository http://repo.cw-ngv.com/juju-clearwater-1/, which is built from a code level without that name change.

(The pinning is done at https://github.com/Metaswitch/clearwater-juju/blob/dnsaas/charms/precise/clearwater-homestead/config.yaml#L10.)

**Comment by thomnico** [comment] 2015-06-09 10:59
Tried following strictly the README ... and I can confirm the yaml are
pinned to ...

But bundle.config.example override to stable !! that is the root cause ..


On Tue, Jun 9, 2015 at 12:51 PM, Rob Day <notifications@github.com> wrote:

> The change in Monit naming (homestead -> homestead_process) shouldn't
> affect the charms - the charms should be using the stable repository
> http://repo.cw-ngv.com/juju-clearwater-1/, which is built from a code
> level without that name change.
>
> (The pinning is done at
> https://github.com/Metaswitch/clearwater-juju/blob/dnsaas/charms/precise/clearwater-homestead/config.yaml#L10.
> )
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Metaswitch/clearwater-juju/issues/21#issuecomment-110317144>
> .
>



-- 
Best Regards,
       Nicolas Thomas
http://insights.ubuntu.com/?p=889
EMEA Solution Architect              Canonical
GPG FPR: D592 4185 F099 9031 6590 6292 492F C740 F03A 7EB9

**Comment by rkd-msw** [comment] 2015-06-09 11:04
Thanks, that makes sense! I'll update https://github.com/Metaswitch/clearwater-juju/blob/dnsaas/bundle-config.yaml.example to pin to `http://repo.cw-ngv.com/juju-clearwater-1/`.

**Comment by thomnico** [comment] 2015-06-09 11:57
Pull request sent (that will validate I can collaborate directly too) .

On Tue, Jun 9, 2015 at 1:04 PM, Rob Day <notifications@github.com> wrote:

> Thanks, that makes sense! I'll update
> https://github.com/Metaswitch/clearwater-juju/blob/dnsaas/bundle-config.yaml.example
> to pin to http://repo.cw-ngv.com/juju-clearwater-1/.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Metaswitch/clearwater-juju/issues/21#issuecomment-110319155>
> .
>



-- 
Best Regards,
       Nicolas Thomas
http://insights.ubuntu.com/?p=889
EMEA Solution Architect              Canonical
GPG FPR: D592 4185 F099 9031 6590 6292 492F C740 F03A 7EB9

**Comment by rkd-msw** [comment] 2015-08-03 10:25
Fixed by #22.

**Closed by rkd-msw** 2015-08-03 10:25 UTC
