### ISSUE TITLE
Juju hook failed: "install" for  unmet dependencies for - libboost-filesystem1.54.0

### ISSUE THREAD

**Issue by Subhranshu** [Metaswitch/clearwater-juju#42] opened 2016-05-18 07:37 UTC
Hi Team, 

I facing the following issue while deploying **clearwater-bono (Current version:
cs:~projectclearwater/precise/clearwater-bono-2)** using **juju version 1.25.5-trusty-amd64** on **Openstack Mitaka** Bootstrapped environment.

The same issue is getting replicated while using **Juju version 2.0-beta6-trusty-amd64** as well 

Looks like something to do with precise repositories, 

Following is the output for **/var/chef-solo/chef-stacktrace.out**
Generated at 2016-05-18 03:30:16 +0000
Chef::Exceptions::Exec: package[clearwater-snmp-alarm-agent] (clearwater::alarms line 35) had an error: Chef::Exceptions::Exec: apt-get -q -y --force-yes install clearwater-snmp-alarm-agent=1.0-160513.165438 returned 100, expected 0
---- Begin output of apt-get -q -y --force-yes install clearwater-snmp-alarm-agent=1.0-160513.165438 ----
STDOUT: Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 clearwater-snmp-alarm-agent : Depends: clearwater-snmpd but it is not going to be installed
                               Depends: libboost-filesystem1.54.0 but it is not installableSTDERR: E: Unable to correct problems, you have held broken packages.
---- End output of apt-get -q -y --force-yes install clearwater-snmp-alarm-agent=1.0-160513.165438 ----

/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/mixin/command.rb:128:in `handle_command_failures'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/mixin/command.rb:75:in `run_command'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/mixin/command.rb:143:in `run_command_with_systems_locale'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/provider/package/apt.rb:97:in `install_package'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/provider/package.rb:82:in `block in action_install'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/mixin/why_run.rb:52:in `call'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/provider.rb:149:in `converge_by'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/provider/package.rb:80:in `action_install'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/provider.rb:114:in `run_action'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/resource.rb:625:in `run_action'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/runner.rb:49:in `run_action'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/runner.rb:81:in `each'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/runner.rb:81:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/resource_collection.rb:98:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/resource_collection.rb:96:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/runner.rb:80:in `converge'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/client.rb:429:in `converge'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/client.rb:494:in `do_run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/client.rb:199:in `block in run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/client.rb:193:in `fork'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/client.rb:193:in `run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/application.rb:183:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/application/solo.rb:239:in `block in run_application'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/application/solo.rb:231:in `loop'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/application/solo.rb:231:in `run_application'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/application.rb:66:in `run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/bin/chef-solo:25:in `<top (required)>'
/usr/bin/chef-solo:23:in `load'
/usr/bin/chef-solo:23:in `<main>'

Kindly suggest
Best Regards
Subhranshu

**Comment by chris-elford-metaswitch** [comment] 2016-05-18 09:52
Hi Subhranshu,

It looks like we've made a lot of changes since we published the charm that you are using (cs:~projectclearwater/precise/clearwater-bono-2), and Project Clearwater now works quite differently.

You should be able to deploy Bono by pulling the latest version of the charm from this GitHub repo.

We will see if we can update the charm on the Charm Store to get it working or, at the very least, remove the broken version.

**Comment by Subhranshu** [comment] 2016-05-19 02:33
Hi Chris,

Thanks for the quick reply, I have actually tested it with almost all versions available on Juju Charm Store, however all have the same issue, following are the versions I have tried already:

**cs:~matt-williams-x/precise/clearwater-bono-5
    ~mat...er-bono-4
    ~mat...er-bono-3
    ~mat...er-bono-2
    ~mat...er-bono-1
    ~mat...er-bono-0**

Also as per your recommendation I am now going to try the solution recommended and proposed in GitHub - https://github.com/Metaswitch/clearwater-juju, and will see how to use juju-deployer fo this,

I also would recommend that if Juju Charm Store is not updated then If there is any way we can update it as well,

Best Regards,
Subhranshu

**Comment by mirw** [comment] 2016-05-19 08:14
It sounds as though there's no way of removing Charms from the charm store.

http://askubuntu.com/questions/504046/how-to-permanently-remove-a-charm-from-the-juju-charms-store

:disappointed:

**Comment by Subhranshu** [comment] 2016-05-19 09:18
Hi Chris, 

I followed the instructions on **github clearwater-juju project page** - https://github.com/Metaswitch/clearwater-juju,

**JUJU version 1.25.5-trusty-amd64**
**precise/clearwater-bono-4**

Following the following steps:
git clone -b dnsaas https://github.com/Metaswitch/clearwater-juju.git
cd clearwater-juju/charms
juju deploy local:precise/clearwater-bono --to 42 --debug

**And Now I have received the following error:-**
2016-05-19 08:46:04 INFO install /var/lib/juju/agents/unit-clearwater-bono-14/charm/hooks/install: line 27: chef-solo: command not found
2016-05-19 08:46:04 INFO juju.worker.uniter.context context.go:579 handling reboot
2016-05-19 08:46:04 ERROR juju.worker.uniter.operation runhook.go:107 hook "install" failed: exit status 127
2016-05-19 08:46:04 DEBUG juju.worker.uniter modes.go:31 [AGENT-STATUS] failed: run install hook
2016-05-19 08:46:05 INFO juju.worker.uniter modes.go:569 ModeContinue exiting
2016-05-19 08:46:05 INFO juju.worker.uniter modes.go:567 ModeHookError starting
2016-05-19 08:46:05 DEBUG juju.worker.uniter.filter filter.go:601 want resolved event
2016-05-19 08:46:05 DEBUG juju.worker.uniter.filter filter.go:595 want forced upgrade true
2016-05-19 08:46:05 DEBUG juju.worker.uniter.filter filter.go:731 no new charm event

Which makes hook "install" fail with chef.solo command not found:
Which I tried replicating manually and seems like some issue with unit-get part of the install script:
~# /var/lib/juju/agents/unit-clearwater-bono-14/charm/hooks/install
/var/lib/juju/agents/unit-clearwater-bono-14/charm/hooks/install: line 5: unit-get: command not found

Please suggest if we can do something about it,

Best Regards,
Subhranshu

**Comment by Subhranshu** [comment] 2016-05-20 06:34
Hi Chris,

I have tried almost everything, would really appreciate if you could suggest something,

Best Regards,
Subhranshu

**Comment by mirw** [comment] 2016-05-20 09:12
I think the `unit-get: command not found` error is a red herring - I don't think you can run charm scripts directly, as the juju wrapper code has to set up an environment in which `unit-get` is available.

It seems as though `chef-solo: command not found` is the issue.  Is `chef-solo` installed on the bono node?  It should be installed automatically by the install hook, but maybe this has silently failed in some way?

**Comment by Subhranshu** [comment] 2016-05-20 11:47
Hi Mir,

While checking the logs again based on your suggestion, that it reports **downloaded metadata file is corrupted or an uncaught error encountered in downloading the file metadata file,**

is this is the problem? 

2016-05-20 11:26:18 INFO install Reading package lists...
2016-05-20 11:26:18 INFO install Building dependency tree...
2016-05-20 11:26:18 INFO install Reading state information...
2016-05-20 11:26:18 INFO install curl is already the newest version.
2016-05-20 11:26:18 INFO install git is already the newest version.
2016-05-20 11:26:18 INFO install libxml2-dev is already the newest version.
2016-05-20 11:26:18 INFO install libxslt1-dev is already the newest version.
2016-05-20 11:26:18 INFO install wget is already the newest version.
2016-05-20 11:26:18 INFO install 0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
2016-05-20 11:26:18 INFO install Downloading Chef 11.6.0 for ubuntu...
2016-05-20 11:26:18 INFO install downloading https://www.opscode.com/chef/metadata?v=11.6.0&prerelease=false&nightlies=false&p=ubuntu&pv=12.04&m=x86_64
2016-05-20 11:26:18 INFO install   to file /tmp/install.sh.6144/metadata.txt
2016-05-20 11:26:18 INFO install trying wget...
2016-05-20 11:26:20 INFO install sha1   5fe8e4e9ddfd8ba66597670f1a1029c3409b9453
2016-05-20 11:26:20 INFO install sha256 1f7360b9cf3af4f5704f5f672c620d480b2776c4d24771ba4d4b590e388baea0
2016-05-20 11:26:20 INFO install url    https://packages.chef.io/stable/ubuntu/12.04/chef_11.6.0-1.ubuntu.12.04_amd64.deb
2016-05-20 11:26:20 INFO install version        11.6.0downloaded metadata file is corrupted or an uncaught error was encountered in downloading the file...
2016-05-20 11:26:20 INFO install Version: 11.6.0
2016-05-20 11:26:20 INFO install
2016-05-20 11:26:20 INFO install Please file a Bug Report at https://github.com/opscode/opscode-omnitruck/issues/new
2016-05-20 11:26:20 INFO install Alternatively, feel free to open a Support Ticket at https://www.getchef.com/support/tickets
2016-05-20 11:26:20 INFO install More Chef support resources can be found at https://www.getchef.com/support
2016-05-20 11:26:20 INFO install
2016-05-20 11:26:20 INFO install Please include as many details about the problem as possible i.e., how to reproduce
2016-05-20 11:26:20 INFO install the problem (if possible), type of the Operating System and its version, etc.,
2016-05-20 11:26:20 INFO install and any other relevant details that might help us with troubleshooting.
2016-05-20 11:26:20 INFO install
2016-05-20 11:26:20 INFO install HEAD is now at 9e0cb1c... Merge pull request #163 from Metaswitch/fix_merge
2016-05-20 11:26:20 INFO install Submodule 'cookbooks/apt' () registered for path 'cookbooks/apt'
2016-05-20 11:26:20 INFO install Submodule 'cookbooks/chef-solo-search' () registered for path 'cookbooks/chef-solo-search'
2016-05-20 11:26:20 INFO worker.uniter.jujuc server.go:172 running hook tool "unit-get" ["private-address"]

Best Regards,
Subhranshu

**Comment by mirw** [comment] 2016-05-23 08:25
Thanks for those logs - yes, it looks like the old installer no longer works.

I tried running the chef-install.sh script directly and it failed the same way:

```
ubuntu@ip-10-232-67-201:~/clearwater-juju/charms/precise/clearwater-bono/lib$ sudo ./chef-install.sh -v 11.6.0
Downloading Chef 11.6.0 for ubuntu...
downloading https://www.opscode.com/chef/metadata?v=11.6.0&prerelease=false&nightlies=false&p=ubuntu&pv=12.04&m=x86_64
  to file /tmp/install.sh.4710/metadata.txt
trying wget...
sha1    5fe8e4e9ddfd8ba66597670f1a1029c3409b9453
sha256  1f7360b9cf3af4f5704f5f672c620d480b2776c4d24771ba4d4b590e388baea0
url     https://packages.chef.io/stable/ubuntu/12.04/chef_11.6.0-1.ubuntu.12.04_amd64.deb
version 11.6.0downloaded metadata file is corrupted or an uncaught error was encountered in downloading the file...
Version: 11.6.0

Please file a Bug Report at https://github.com/opscode/opscode-omnitruck/issues/new
Alternatively, feel free to open a Support Ticket at https://www.getchef.com/support/tickets
More Chef support resources can be found at https://www.getchef.com/support

Please include as many details about the problem as possible i.e., how to reproduce
the problem (if possible), type of the Operating System and its version, etc.,
and any other relevant details that might help us with troubleshooting.
```

Running the individual commands in the install script, I found that the HTTPS certificate presented by packages.chef.io is not valid:

```
ubuntu@ip-10-232-67-201:~/clearwater-juju/charms/precise/clearwater-bono/lib$ wget https://packages.chef.io/stable/ubuntu/12.04/chef_11.6.0-1.ubuntu.12.04_amd64.deb
--2016-05-23 08:17:06--  https://packages.chef.io/stable/ubuntu/12.04/chef_11.6.0-1.ubuntu.12.04_amd64.deb
Resolving packages.chef.io (packages.chef.io)... 108.168.243.150, 75.126.118.188
Connecting to packages.chef.io (packages.chef.io)|108.168.243.150|:443... connected.
ERROR: no certificate subject alternative name matches
        requested host name `packages.chef.io'.
To connect to packages.chef.io insecurely, use `--no-check-certificate'.
```

Running with `--no-check-certificate` succeeds, and also gives us the clue that chef.io seems to have migrated to the akamai CDN for content distribution, but have not set up certificates correctly for this:

```
ubuntu@ip-10-232-67-201:~/clearwater-juju/charms/precise/clearwater-bono/lib$ wget --no-check-certificate https://packages.chef.io/stable/ubuntu/12.04/chef_11.6.0-1.ubuntu.12.04_amd64.deb
--2016-05-23 08:17:22--  https://packages.chef.io/stable/ubuntu/12.04/chef_11.6.0-1.ubuntu.12.04_amd64.deb
Resolving packages.chef.io (packages.chef.io)... 75.126.118.188, 108.168.243.150
Connecting to packages.chef.io (packages.chef.io)|75.126.118.188|:443... connected.
WARNING: no certificate subject alternative name matches
        requested host name `packages.chef.io'.
HTTP request sent, awaiting response... 302
Location: https://akamai.bintray.com/1f/1f7360b9cf3af4f5704f5f672c620d480b2776c4d24771ba4d4b590e388baea0?__gda__=exp=1463992162~hmac=8a49fe83dd688c914c5543143956b7757e66ab18d42e4725650d93b321bfdfb8&response-content-disposition=attachment%3Bfilename%3D%22chef_11.6.0-1.ubuntu.12.04_amd64.deb%22&response-content-type=application%2Foctet-stream [following]
--2016-05-23 08:17:22--  https://akamai.bintray.com/1f/1f7360b9cf3af4f5704f5f672c620d480b2776c4d24771ba4d4b590e388baea0?__gda__=exp=1463992162~hmac=8a49fe83dd688c914c5543143956b7757e66ab18d42e4725650d93b321bfdfb8&response-content-disposition=attachment%3Bfilename%3D%22chef_11.6.0-1.ubuntu.12.04_amd64.deb%22&response-content-type=application%2Foctet-stream
Resolving akamai.bintray.com (akamai.bintray.com)... 23.14.147.203
Connecting to akamai.bintray.com (akamai.bintray.com)|23.14.147.203|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 24625814 (23M) [application/octet-stream]
Saving to: `chef_11.6.0-1.ubuntu.12.04_amd64.deb'

100%[===================================================================================================================>] 24,625,814  7.63M/s   in 3.1s

2016-05-23 08:17:25 (7.63 MB/s) - `chef_11.6.0-1.ubuntu.12.04_amd64.deb' saved [24625814/24625814]
```

When we check this binary package, we find it matches the expected `sha1sum` and `sha256sum` checksums.

So it looks as though chef has broken back-compability on their install process.

I need to see if someone has time to look at this - I'm not going to be able to do so in the next couple of days.

**Comment by mirw** [comment] 2016-05-23 09:56
Actually, it looks like the issue is with them moving from MD5 to SHA1.

**Comment by Subhranshu** [comment] 2016-05-23 11:49
Hi Mir,

Thanks for the help, and I really appreciate your support here 

I also tried the same and the results are exactly identical,

Please also post me as well in case you get resolution for it, really wish to see this working,

Best Regards,
Subhranshu

**Comment by mirw** [comment] 2016-05-23 12:58
@Subhranshu, I've just merged a fix.  Please can you try

*   switching from the `dnsaas` branch to the `master` branch (`git checkout master`)
*   pulling the latest code (`git pull`)
*   re-running your test?

Thanks!

**Comment by Subhranshu** [comment] 2016-05-24 06:06
Hi Mir,

Thank you so much for your help,

I just ran the test with bono charm from master branch and it works smoothly,

And that solves the problem, bono worked smoothly,

Now I will try bringing all the relations together and will confirm if everything goes fine,

Really appreciate your help on this, 

Best Regards,
Subhranshu Dwivedi

**Comment by mirw** [comment] 2016-05-24 07:38
Thanks for confirming - I'm glad it's working correctly for you now!

**Closed by mirw** 2016-05-24 07:38 UTC
Labels: bug, medium-priority
